// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPNZN7xKca6olQNBZIS1XYQyzO-y7MrLg',
    appId: '1:93637521925:web:11bfc4852c6b77b44ee26c',
    messagingSenderId: '93637521925',
    projectId: 'medisync-86682',
    authDomain: 'medisync-86682.firebaseapp.com',
    storageBucket: 'medisync-86682.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwcpY8D6T7DLVMceb0RHFds2OzT4S95pE',
    appId: '1:93637521925:android:995832a33b78d0984ee26c',
    messagingSenderId: '93637521925',
    projectId: 'medisync-86682',
    storageBucket: 'medisync-86682.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWWc3tx95-9hjjMl-rbm5l6xgYwrnqkLk',
    appId: '1:93637521925:ios:03d53a898891bba44ee26c',
    messagingSenderId: '93637521925',
    projectId: 'medisync-86682',
    storageBucket: 'medisync-86682.firebasestorage.app',
    iosBundleId: 'com.example.medisync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWWc3tx95-9hjjMl-rbm5l6xgYwrnqkLk',
    appId: '1:93637521925:ios:03d53a898891bba44ee26c',
    messagingSenderId: '93637521925',
    projectId: 'medisync-86682',
    storageBucket: 'medisync-86682.firebasestorage.app',
    iosBundleId: 'com.example.medisync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPNZN7xKca6olQNBZIS1XYQyzO-y7MrLg',
    appId: '1:93637521925:web:f610c85744f235224ee26c',
    messagingSenderId: '93637521925',
    projectId: 'medisync-86682',
    authDomain: 'medisync-86682.firebaseapp.com',
    storageBucket: 'medisync-86682.firebasestorage.app',
  );
}
